---
title: "Replication of Support for Resettling Refugees: The Role of Fixed Versus Growth Mind-Sets by Madan et. al. (2019, Psychological Science)"
author: "Ethan Roy ethanroy@stanford.edu"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: false
---

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

## Introduction

For this projet, I plan to replicate Madan et. al.'s 2019 study, which explores the connection between a fixed versus growth mindset and how those mindsets impact an individual's openness to supporting refugees in their country. Though my research interests align more closely with the field of educational neuroscience, I am intrigued by the impact a growth mindset can have on student's learning. By replicating this study, I will be able to reflect more on the impact of mindset (growth or fixed) on an individuals openness to new people, cultures, and ways of thinking.  

### Study Description

The study being replicated explored the effect of mindset on an individual's support for refugees in their country. In a series of six experiments, the original authors examined the mindsets (growth or fixed) of individuals in the United States and United Kingdom and their views on if refugees are able to assimilate into a new culture and to what extent are refugees obligated to assimilate to a new society. I plan to replicate the first study, which leverages survey data to ascertain a participant's support for refugees based on their opinions on the type of person someone is, mindset regarding intelligence (fixed vs growth), and political leanings.

#### Stimuli and Procedures

Participants will be recruited through Amazon Mechanical Turk. Per the original study, participants will report some demographic information (gender, age, race). Each participant will have to undergo a pre-screening to ensure that they meet two criteria:

* are a United States Citizen
* currently residing in the United States

Once participants have been screened, they will read a breif paragraph outlining the  refugee resettlement policy of the United States announced by the president in September of 2016. They will then answer a four item questionaire to measure their support for resettling refugees and two eight item questionaires measuring their views on the type of person someone is and their mindsets regarding participants. Participants will be randomly assigned so that half of sample responds to the refugee measure first and half of the sample responds to the mindsets measure first. Finally, participants will respond to a three item survey measuring their political orientation. 

#### Potential Challenges

While replicating this study, I foresee the following challenges:

* having a sufficient sample size to generate a sufficient effect size that also meets the bugetary criteria for this replication
* having enough participants after excluding participants who do not meet the inclusion criteria
* subjects not feeling as strongly about the current U.S refugee resettlement policy due to other political happenings moving into the public spotlight.

### Links

* [Project Repository](https://github.com/psych251/mandan2019)
* [Original Paper](https://github.com/psych251/mandan2019/blob/master/original_paper/mandan2019.pdf)

## Methods

### Power Analysis

Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size.  Considerations of feasibility for selecting planned sample size.

### Planned Sample

The planned sample for this replication will be **[need to do power analysis]** participants based on the power analysis conducted above. Participants will be screened to ensure that they are citizens of the United States and currently residing in the United States.

### Materials

As quoted from original study:

"We administered four items to measure participants’ support for resettling refugees, each measured on a 7-point scale: (a) “How much do you agree that the US should take in 110,000 refugees in the next 12 months?” (*strongly disagree to strongly agree*), (b) “How much do you support the policy that the US should take in 110,000 refugees in the next 12 months?” (*strongly against to strongly support*), (c) “Do you think that the United States is taking in too many refugees?” (reverse-coded; *definitely not to definitely yes*), and (d) “Do you think that the United States is taking in too few refugees?” (*definitely not to definitely yes*).

We measured participants’ mind-sets about the kind of person someone is using an established eight-item scale (Levy et al., 1998; sample item: “The kind of person someone is, is something basic about them, and it can’t be changed very much”). We also measured participants’ mind-set about intelligence (fixed vs. growth) using the standard eight-item scale (Dweck, 2000; sample item: “People have a certain amount of intelligence, and they can’t really do much to change it”). For both scales, all items were scored such that higher numbers indicated stronger growth kind-of-person mind-sets or mind-sets about intelligence.

Finally, because the question of accepting refugees is a highly politicized issue, we measured participants’ political orientation using three items, each measured on a 7-point scale ranging from *strongly conservative* to *strongly liberal* (Item 1), *strongly right* to *strongly left* (Item 2), and *strongly Republican* to *strongly Democrat* (Item 3)."

The exact items, measures, and scales were used in this replication.


### Procedure	

As quoted from original study: 

We presented participants with the following paragraph detailing the latest refugee resettlement policy of the United States, which was announced by the U.S. president in September 2019:

>The United States recently revised its policy towards refugees. The President recently signed an order that set the cap on the number of refugees admitted to the United States next year at 18,000, the lowest level since the program began four decades ago. This new cap is down from the last years limit of 30,000. This is the third consecutive year the U.S has reduced the limit of refugees admitted to the United States.  

Participants were then asked to respond to the three measures described in the [Materials]. Half of the participants were randomly assigned to respond to the resettling refugees measure first while the other half responded to the mindsets measures first. After responding to both of those measures, participants responded to the political orientation measures.


### Analysis Plan

First, participants who are not U.S citizens or are U.S citizens living abroad will be excluded from the final sample. 

Next, I will calculate descriptive statistics for each variable (kind of person mindsets, mindsets about intelligence, political orientation, and support for resettling refugees). 

**Key Analysis of Interest:**

"[I will] conduct a linear regression with participants’ support for resettling refugees as the dependent measure and their kind-of-person mind-sets, mind-sets about intelligence, and political orientation as independent variables"
 

### Differences from Original Study

To ensure stable correlations, the original study recruited 400 participants, even though their power analysis indicated they needed 94 participants. Due to budgetary constrains, this replication will likely have a much smaller sample size than the original. 

Per the suggestion of the original author, participants were asked to read a summary of the most recent refugee policy of the United States, instead of the 2016 policy, the year the original study was conducted.

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


## Results


### Data preparation

At this time in the replication I do not have any data to prepare and do not have a clear picture of how the raw data look from MTurk. However, I will have to exclude any participants who do not meet the two inclusion criteria. Additionally, if MTurk does not provide a unique subect ID number for each participant, I will have to create a new entry for each item that assigns each participant a subject ID number. I will also have to gather the raw data into a long form dataframe so that they work well within the tidyverse. Once the data are in long form, I will have to re-label columns for each measure (support for resettling refugees, kind-of-person mind-sets, mind-sets about intelligence, and political orientation) so that I can group based on the type of measure and calculate the descritpive statistics for each measure.
	
```{r include=F}
###Data Preparation

####Load Relevant Libraries and Functions

####Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Participant Demographics

A brief analysis will be conducted on the demographic measures to get an understanding of the demographic makeup of the sample. Factors that will be looked at include gender, age, and race.

### Confirmatory analysis

As done in the original study, I plan to build three linear models. The first one will look at how mindsets about intelligence predict support for refugees. The next model will add political orientation to the independent variables and the third model will add kind of person mindsets. I will also run another regression examining the effect the order of the survey measures (support for resettling refugees measure first or mindsets measures first) has on participant's support for resettling refugees.


Due to the nature of the regressions, the original paper has no figures. I could include a graph of the first linear model I build but I'm not sure how much value that would add to the replication. 
*Side-by-side graph with original graph is ideal here*

### Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
